model:
  num_classes: 5
  seg_channels: 1
  pretrained: true

training:
  num_epochs: 20
  batch_size: 8
  learning_rate: 0.001
  alpha: 1.0
  beta: 1.0
  device: cuda

paths:
  classification_image_dir: /Users/balmukundmishra/Desktop/2025-Learning/Eye_Disease_Detection_MTL/data/IDRID_1/Images/Classification
  segmentation_image_dir: /Users/balmukundmishra/Desktop/2025-Learning/Eye_Disease_Detection_MTL/data/IDRID_1/Images/Segmentation
  mask_dir: /Users/balmukundmishra/Desktop/2025-Learning/Eye_Disease_Detection_MTL/data/IDRID_1/Masks
  label_file: /Users/balmukundmishra/Desktop/2025-Learning/Eye_Disease_Detection_MTL/data/IDRID_1/labels.json